# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required

services:
  - docker

before_install:
  - docker pull -a nielsad/travis-lazarus

script:
  - docker run -v $TRAVIS_BUILD_DIR:/build nielsad/travis-lazarus:latest-amd64 bash -c "lazbuild my_lazarus_tests.lpi && ./bin/my_lazarus_tests --all --format=plain"
  - docker run -v $TRAVIS_BUILD_DIR:/build nielsad/travis-lazarus:1.4-amd64  bash -c "lazbuild my_lazarus_tests.lpi && ./bin/my_lazarus_tests --all --format=plain"

  - docker run -v $TRAVIS_BUILD_DIR:/build nielsad/travis-lazarus:latest-i386 bash -c "lazbuild my_lazarus_tests.lpi && ./bin/my_lazarus_tests --all --format=plain"
  - docker run -v $TRAVIS_BUILD_DIR:/build nielsad/travis-lazarus:1.4-i386  bash -c "lazbuild my_lazarus_tests.lpi && ./bin/my_lazarus_tests --all --format=plain"

notifications:
  email:
    on_success: false
    on_failure: change
