# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

sudo: true

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - USE_PKG_MAN=true # Use the latest version from the default package manager
    - LAZ_VER=1.0.14
    - LAZ_VER=1.2.6
    - LAZ_VER=1.4.4
    - LAZ_VER=1.2.6 LAZ_WINE=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - LAZ_VER=1.4.4 LAZ_WINE=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_install:
  - sh -e /etc/init.d/xvfb start || true

install:
  - ./.travis.install.py

script:
  - $LAZ_WINE lazbuild $LAZ_OPT my_lazarus_tests.lpi
  - $LAZ_WINE ./bin/my_lazarus_tests --all --format=plain
